"""Phase 2 — Breed seed script. Run: python -m app.scripts.seed_breeds"""
from datetime import datetime
import uuid

BREEDS_DATA = [
    {
        "breed_name": "Labrador Retriever",
        "aliases": ["Lab"],
        "origin_country": "Canada/UK",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "29-36",
        "female_weight_range_kg": "25-32",
        "height_range_cm": "55-62",
        "coat_type": "double coat",
        "shedding_level": "high",
        "grooming_need": "medium",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "high",
        "joint_risk": "high",
        "skin_risk": "medium",
        "ear_risk": "high",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["friendly", "outgoing", "even-tempered"],
        "training_difficulty": "easy",
        "food_cautions": ["Prone to obesity, measure meals strictly"],
        "nutrition_notes": "Measure meals strictly to avoid weight gain.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Labs easily hide fat under their coat. Ribs should be palpable without excess fat covering.",
        "puppy_care_notes": "Large breed puppy formula to ensure steady growth and protect joints.",
        "adult_care_notes": "Monitor weight; regular exercise is key.",
        "senior_care_notes": "Joint supplements like glucosamine often recommended.",
        "vaccination_context": "Core vaccines annually. Leptospirosis recommended in India.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Rapid weight gain", "Joint swelling", "Exercise intolerance", "Bloat/GDV"],
        "common_owner_questions": ["Why is my Lab gaining weight?", "Are ear infections common?"],
        "safe_ai_response_rules": ["Emphasize portion control", "Always advise vet check for chronic ear issues"],
        "vet_escalation_rules": ["Escalate limping in puppies", "Escalate signs of bloat"],
        "source_references": ["WSAVA", "AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "German Shepherd",
        "aliases": ["GSD", "Alsatian"],
        "origin_country": "Germany",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "9-13",
        "male_weight_range_kg": "30-40",
        "female_weight_range_kg": "22-32",
        "height_range_cm": "55-65",
        "coat_type": "double coat",
        "shedding_level": "high",
        "grooming_need": "high",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 90,
        "apartment_suitability": "poor",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "low",
        "joint_risk": "high",
        "skin_risk": "medium",
        "ear_risk": "medium",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "medium",
        "dental_risk": "low",
        "digestive_sensitivity": "high",
        "behavior_tendency": ["loyal", "protective", "intelligent"],
        "training_difficulty": "easy",
        "food_cautions": ["Avoid foods that cause flatulence due to bloat risk"],
        "nutrition_notes": "Highly digestible diet needed due to sensitive stomach.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Should have a clear waist when viewed from above.",
        "puppy_care_notes": "Slow growth is crucial to protect hips and elbows.",
        "adult_care_notes": "Mental stimulation is as important as physical exercise.",
        "senior_care_notes": "Watch for signs of degenerative myelopathy and hip dysplasia.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Bloat/GDV — bloated belly", "Hind-leg weakness", "Degenerative myelopathy"],
        "common_owner_questions": ["Is my GSD's sloping back normal?", "How to prevent bloat?"],
        "safe_ai_response_rules": ["Always warn about GDV with GI symptoms"],
        "vet_escalation_rules": ["Escalate bloated abdomen immediately", "Escalate sudden hind limb weakness"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Golden Retriever",
        "aliases": ["Golden"],
        "origin_country": "UK (Scotland)",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "29-34",
        "female_weight_range_kg": "25-29",
        "height_range_cm": "51-61",
        "coat_type": "double coat",
        "shedding_level": "high",
        "grooming_need": "high",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "medium",
        "joint_risk": "high",
        "skin_risk": "high",
        "ear_risk": "high",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "medium",
        "dental_risk": "low",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["intelligent", "friendly", "devoted"],
        "training_difficulty": "easy",
        "food_cautions": ["Avoid overfeeding"],
        "nutrition_notes": "Cancer-preventive antioxidant-rich diet advised.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Thick coat can hide waist, rely on feeling the ribs.",
        "puppy_care_notes": "Socialize early and monitor diet for steady growth.",
        "adult_care_notes": "Regular brushing to manage shedding and check for skin issues.",
        "senior_care_notes": "Regular vet visits crucial due to high cancer risk.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Lumps or masses", "Pale gums", "Exercise intolerance"],
        "common_owner_questions": ["What to do about hot spots?", "Why is my Golden limping?"],
        "safe_ai_response_rules": ["Advise vet check for any new lumps"],
        "vet_escalation_rules": ["Escalate pale gums or collapse", "Escalate rapidly growing masses"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Pug",
        "aliases": ["Carlin", "Mops"],
        "origin_country": "China",
        "india_commonness_level": "common",
        "size_group": "toy",
        "life_expectancy_range": "13-15",
        "male_weight_range_kg": "6-8",
        "female_weight_range_kg": "6-8",
        "height_range_cm": "25-33",
        "coat_type": "short coat",
        "shedding_level": "high",
        "grooming_need": "medium",
        "activity_level": "low",
        "exercise_need_minutes_per_day": 20,
        "apartment_suitability": "good",
        "heat_sensitivity": "high",
        "cold_sensitivity": "medium",
        "obesity_risk": "high",
        "joint_risk": "medium",
        "skin_risk": "high",
        "ear_risk": "medium",
        "eye_risk": "high",
        "respiratory_risk": "high",
        "heart_risk": "low",
        "dental_risk": "high",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["charming", "mischievous", "loving"],
        "training_difficulty": "medium",
        "food_cautions": ["Very prone to obesity, strict calorie control needed"],
        "nutrition_notes": "Low-calorie diet. Use dental kibbles if possible.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Should not look like a barrel. Waist must be visible behind ribs.",
        "puppy_care_notes": "Clean facial folds daily.",
        "adult_care_notes": "Keep out of heat. Exercise only in cool weather.",
        "senior_care_notes": "Watch for signs of arthritis and breathing issues.",
        "vaccination_context": "Core vaccines. Avoid stress during vet visits.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Breathing difficulty", "Eye prolapse", "Overheating/heatstroke", "Blue gums"],
        "common_owner_questions": ["Is snoring normal?", "How to clean face wrinkles?"],
        "safe_ai_response_rules": ["Treat any respiratory distress as emergency"],
        "vet_escalation_rules": ["Escalate breathing difficulty", "Escalate eye injuries immediately"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Beagle",
        "aliases": ["English Beagle"],
        "origin_country": "UK",
        "india_commonness_level": "common",
        "size_group": "small",
        "life_expectancy_range": "10-15",
        "male_weight_range_kg": "10-11",
        "female_weight_range_kg": "9-10",
        "height_range_cm": "33-41",
        "coat_type": "short coat",
        "shedding_level": "medium",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 45,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "low",
        "cold_sensitivity": "medium",
        "obesity_risk": "high",
        "joint_risk": "low",
        "skin_risk": "low",
        "ear_risk": "high",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "medium",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["merry", "friendly", "curious"],
        "training_difficulty": "high",
        "food_cautions": ["Will overeat if allowed. Secure garbage cans."],
        "nutrition_notes": "Food-motivated breed — portion control critical.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Tends to be stocky, but a waist should be visible.",
        "puppy_care_notes": "Start training and socialization early.",
        "adult_care_notes": "Needs significant daily exercise. Keep on leash (scent hound).",
        "senior_care_notes": "Monitor weight closely as activity drops.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Epilepsy signs", "Cherry eye", "Severe ear infections"],
        "common_owner_questions": ["Why is my Beagle howling?", "How to stop them eating everything?"],
        "safe_ai_response_rules": ["Remind owners of food motivation and toxicity risks (e.g. eating chocolate)"],
        "vet_escalation_rules": ["Escalate seizures", "Escalate sudden pain (IVDD risk)"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Shih Tzu",
        "aliases": ["Chrysanthemum Dog"],
        "origin_country": "Tibet/China",
        "india_commonness_level": "common",
        "size_group": "toy",
        "life_expectancy_range": "10-18",
        "male_weight_range_kg": "4-7",
        "female_weight_range_kg": "4-7",
        "height_range_cm": "20-28",
        "coat_type": "long coat",
        "shedding_level": "low",
        "grooming_need": "high",
        "activity_level": "low",
        "exercise_need_minutes_per_day": 20,
        "apartment_suitability": "good",
        "heat_sensitivity": "high",
        "cold_sensitivity": "medium",
        "obesity_risk": "medium",
        "joint_risk": "low",
        "skin_risk": "medium",
        "ear_risk": "high",
        "eye_risk": "high",
        "respiratory_risk": "high",
        "heart_risk": "low",
        "dental_risk": "high",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["affectionate", "playful", "outgoing"],
        "training_difficulty": "medium",
        "food_cautions": ["Feed small kibble to prevent choking and aid digestion"],
        "nutrition_notes": "Small frequent meals. Watch for dental disease.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Long coat hides body condition, need to physically feel the ribs.",
        "puppy_care_notes": "Start grooming training early.",
        "adult_care_notes": "Daily brushing required if kept in long coat.",
        "senior_care_notes": "Dental care is paramount.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Eye injury", "Breathing obstruction", "Overheating"],
        "common_owner_questions": ["How to clean tear stains?", "Why are they reverse sneezing?"],
        "safe_ai_response_rules": ["Eye issues in Shih Tzus are always urgent"],
        "vet_escalation_rules": ["Escalate any eye redness or squinting", "Escalate breathing distress"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Rottweiler",
        "aliases": ["Rottie"],
        "origin_country": "Germany",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "9-10",
        "male_weight_range_kg": "43-61",
        "female_weight_range_kg": "36-45",
        "height_range_cm": "56-69",
        "coat_type": "short coat",
        "shedding_level": "medium",
        "grooming_need": "low",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "poor",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "medium",
        "joint_risk": "high",
        "skin_risk": "low",
        "ear_risk": "low",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "high",
        "dental_risk": "low",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["loyal", "confident", "guardian"],
        "training_difficulty": "medium",
        "food_cautions": ["Do not exercise immediately after eating (bloat risk)"],
        "nutrition_notes": "High-quality protein. Joint support supplements from age 4.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Muscular build, but should not have excess fat over ribs.",
        "puppy_care_notes": "Extensive socialization is mandatory.",
        "adult_care_notes": "Needs a job or structured training to prevent boredom.",
        "senior_care_notes": "High risk of osteosarcoma (bone cancer); monitor for limping.",
        "vaccination_context": "Core vaccines. Highly susceptible to Parvovirus as puppies.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Bloat/GDV", "Osteosarcoma signs (sudden severe limping)", "Heart issues (coughing, collapse)"],
        "common_owner_questions": ["Is it normal for them to be protective?", "Why is my puppy limping?"],
        "safe_ai_response_rules": ["Treat puppy diarrhea very seriously due to parvo risk"],
        "vet_escalation_rules": ["Escalate sudden lethargy or collapse", "Escalate severe lameness"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Indian Pariah Dog",
        "aliases": ["INDog", "Desi Kutta"],
        "origin_country": "India",
        "india_commonness_level": "common",
        "size_group": "medium",
        "life_expectancy_range": "13-15",
        "male_weight_range_kg": "20-30",
        "female_weight_range_kg": "15-25",
        "height_range_cm": "46-64",
        "coat_type": "short coat",
        "shedding_level": "medium",
        "grooming_need": "low",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 45,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "low",
        "cold_sensitivity": "medium",
        "obesity_risk": "low",
        "joint_risk": "low",
        "skin_risk": "low",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["alert", "social", "highly trainable"],
        "training_difficulty": "medium",
        "food_cautions": ["Usually not fussy, but avoid sudden diet changes"],
        "nutrition_notes": "Hardy breed. Balanced commercial or home diet.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Naturally lean and athletic.",
        "puppy_care_notes": "Early socialization is important if adopted from street.",
        "adult_care_notes": "Very low maintenance.",
        "senior_care_notes": "Generally healthy, monitor dental health.",
        "vaccination_context": "Core vaccines essential. Rabies mandatory by law.",
        "deworming_context": "Every 3 months. High tick/flea exposure in India.",
        "emergency_red_flags_for_breed": ["Tick fever signs (lethargy, pale gums, fever)", "Mange spreading rapidly"],
        "common_owner_questions": ["How to get rid of ticks?", "Is home food okay?"],
        "safe_ai_response_rules": ["Always warn about tick fever for lethargic Indian street dogs"],
        "vet_escalation_rules": ["Escalate pale gums or high fever"],
        "source_references": ["WSAVA India Guidelines"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Dachshund",
        "aliases": ["Sausage Dog", "Doxie"],
        "origin_country": "Germany",
        "india_commonness_level": "moderate",
        "size_group": "small",
        "life_expectancy_range": "12-16",
        "male_weight_range_kg": "7-15",
        "female_weight_range_kg": "7-15",
        "height_range_cm": "20-23",
        "coat_type": "varies (smooth, wire, long)",
        "shedding_level": "low",
        "grooming_need": "medium",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 30,
        "apartment_suitability": "good",
        "heat_sensitivity": "low",
        "cold_sensitivity": "high",
        "obesity_risk": "high",
        "joint_risk": "high",
        "skin_risk": "low",
        "ear_risk": "medium",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "high",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["clever", "stubborn", "devoted"],
        "training_difficulty": "high",
        "food_cautions": ["Obesity significantly increases risk of spinal issues (IVDD)"],
        "nutrition_notes": "Strict weight management. Avoid stairs and jumping.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Must maintain visible waist. Even 1kg overweight is dangerous for their back.",
        "puppy_care_notes": "Teach them to use ramps instead of jumping.",
        "adult_care_notes": "Support both ends when picking them up.",
        "senior_care_notes": "Monitor back health and dental tartar.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Back pain or paralysis (IVDD)", "Sudden hind limb weakness", "Dragging back legs"],
        "common_owner_questions": ["Why is my Dachshund dragging his back legs?", "How to prevent back issues?"],
        "safe_ai_response_rules": ["Any back pain or hind limb weakness is an absolute emergency"],
        "vet_escalation_rules": ["Escalate inability to walk or urinate", "Escalate signs of pain when picked up"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Doberman",
        "aliases": ["Doberman Pinscher", "Dobie"],
        "origin_country": "Germany",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "40-45",
        "female_weight_range_kg": "32-35",
        "height_range_cm": "61-71",
        "coat_type": "short coat",
        "shedding_level": "low",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "poor",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "high",
        "obesity_risk": "low",
        "joint_risk": "medium",
        "skin_risk": "medium",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "high",
        "dental_risk": "low",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["fearless", "loyal", "alert"],
        "training_difficulty": "medium",
        "food_cautions": ["Do not exercise right after eating (bloat risk)"],
        "nutrition_notes": "High protein. Cardiac screening annually after age 2.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Should be athletic and lean, ribs palpable.",
        "puppy_care_notes": "Extensive socialization needed.",
        "adult_care_notes": "Mental and physical exercise are mandatory.",
        "senior_care_notes": "Dilated cardiomyopathy (DCM) is highly prevalent; monitor for coughing/fainting.",
        "vaccination_context": "Core + Leptospirosis.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Sudden collapse (DCM)", "Wobbling (Wobbler's syndrome)", "Fainting", "Bloat"],
        "common_owner_questions": ["Is fainting normal?", "How to train my Doberman?"],
        "safe_ai_response_rules": ["Treat coughing or fainting as urgent cardiac signs"],
        "vet_escalation_rules": ["Escalate collapse", "Escalate bloated abdomen"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Pomeranian",
        "aliases": ["Pom"],
        "origin_country": "Germany/Poland",
        "india_commonness_level": "common",
        "size_group": "toy",
        "life_expectancy_range": "12-16",
        "male_weight_range_kg": "1.9-3.5",
        "female_weight_range_kg": "1.9-3.5",
        "height_range_cm": "15-18",
        "coat_type": "double coat",
        "shedding_level": "medium",
        "grooming_need": "high",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 30,
        "apartment_suitability": "good",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "medium",
        "joint_risk": "low",
        "skin_risk": "medium",
        "ear_risk": "low",
        "eye_risk": "medium",
        "respiratory_risk": "high",
        "heart_risk": "low",
        "dental_risk": "high",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["inquisitive", "bold", "vocal"],
        "training_difficulty": "medium",
        "food_cautions": ["Prone to hypoglycemia as puppies"],
        "nutrition_notes": "Small kibble. Dental hygiene critical.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Coat obscures shape, use hands to feel ribs.",
        "puppy_care_notes": "Feed small amounts frequently to avoid low blood sugar.",
        "adult_care_notes": "Use a harness, not a collar, to protect the trachea.",
        "senior_care_notes": "Severe dental issues common; monitor heart.",
        "vaccination_context": "Core vaccines. Toy breeds may be sensitive; discuss with vet.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Tracheal collapse (honking cough)", "Hypoglycaemia in puppies (seizures/lethargy)"],
        "common_owner_questions": ["Why does my Pom sound like a goose?", "How to brush their teeth?"],
        "safe_ai_response_rules": ["Lethargy in a Pom puppy is a hypoglycemia emergency"],
        "vet_escalation_rules": ["Escalate puppy seizures", "Escalate severe honking cough/blue gums"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Siberian Husky",
        "aliases": ["Husky"],
        "origin_country": "Russia",
        "india_commonness_level": "moderate",
        "size_group": "medium",
        "life_expectancy_range": "12-14",
        "male_weight_range_kg": "20-27",
        "female_weight_range_kg": "16-23",
        "height_range_cm": "50-60",
        "coat_type": "double coat",
        "shedding_level": "high",
        "grooming_need": "high",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 90,
        "apartment_suitability": "poor",
        "heat_sensitivity": "high",
        "cold_sensitivity": "low",
        "obesity_risk": "low",
        "joint_risk": "medium",
        "skin_risk": "medium",
        "ear_risk": "low",
        "eye_risk": "high",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["outgoing", "mischievous", "stubborn"],
        "training_difficulty": "high",
        "food_cautions": ["They eat surprisingly little for their size. Avoid overfeeding."],
        "nutrition_notes": "High exercise demand. Keep indoors during Indian summers.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Should feel lean under thick coat.",
        "puppy_care_notes": "Need secure fencing, notorious escape artists.",
        "adult_care_notes": "DO NOT shave their coat in summer; it disrupts temperature regulation.",
        "senior_care_notes": "Monitor for cataracts and progressive retinal atrophy (PRA).",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Heatstroke (excessive panting, collapse)", "Eye conditions (cloudy eyes)"],
        "common_owner_questions": ["Should I shave my Husky in summer?", "Why won't they eat?"],
        "safe_ai_response_rules": ["Always warn against shaving double-coated dogs", "Treat heat exhaustion as urgent"],
        "vet_escalation_rules": ["Escalate signs of heatstroke immediately"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Great Dane",
        "aliases": ["German Mastiff"],
        "origin_country": "Germany",
        "india_commonness_level": "moderate",
        "size_group": "giant",
        "life_expectancy_range": "7-10",
        "male_weight_range_kg": "54-90",
        "female_weight_range_kg": "45-59",
        "height_range_cm": "71-86",
        "coat_type": "short coat",
        "shedding_level": "medium",
        "grooming_need": "low",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 45,
        "apartment_suitability": "poor",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "medium",
        "obesity_risk": "medium",
        "joint_risk": "high",
        "skin_risk": "low",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "high",
        "dental_risk": "low",
        "digestive_sensitivity": "high",
        "behavior_tendency": ["friendly", "patient", "dependable"],
        "training_difficulty": "medium",
        "food_cautions": ["Do not use raised feeders (increases bloat risk)."],
        "nutrition_notes": "Large-breed puppy food only to prevent bone disorders. No free-feeding.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Ribs should be faintly visible.",
        "puppy_care_notes": "Crucial to keep lean and not over-exercise while bones are growing.",
        "adult_care_notes": "Prevent bloat: multiple small meals, rest after eating.",
        "senior_care_notes": "Monitor heart health and joint mobility.",
        "vaccination_context": "Core + Leptospirosis.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Bloat/GDV (unproductive retching, swollen belly)", "Dilated cardiomyopathy", "Wobbler syndrome"],
        "common_owner_questions": ["What is a gastropexy?", "Why is my Dane limping?"],
        "safe_ai_response_rules": ["GDV is the leading cause of death; treat any GI signs with high caution"],
        "vet_escalation_rules": ["Escalate unproductive vomiting/retching immediately", "Escalate collapse"],
        "source_references": ["AAHA", "WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Boxer",
        "aliases": ["Deutscher Boxer"],
        "origin_country": "Germany",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "27-32",
        "female_weight_range_kg": "25-29",
        "height_range_cm": "53-63",
        "coat_type": "short coat",
        "shedding_level": "medium",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "high",
        "cold_sensitivity": "high",
        "obesity_risk": "low",
        "joint_risk": "medium",
        "skin_risk": "high",
        "ear_risk": "low",
        "eye_risk": "medium",
        "respiratory_risk": "high",
        "heart_risk": "high",
        "dental_risk": "medium",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["fun-loving", "active", "devoted"],
        "training_difficulty": "medium",
        "food_cautions": ["Prone to bloat. Deep-chested."],
        "nutrition_notes": "High energy. Brachycephalic — avoid heat exercise.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Athletic and muscular. Last 1-2 ribs often naturally visible.",
        "puppy_care_notes": "Can be very boisterous, early training needed.",
        "adult_care_notes": "Heat sensitive due to short muzzle. Check any new skin lumps.",
        "senior_care_notes": "High risk for cancers (mast cell tumors) and heart conditions (Boxer cardiomyopathy).",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Breathing difficulty", "Heart arrhythmia (fainting)", "Mast cell tumours", "Bloat"],
        "common_owner_questions": ["What is this lump?", "Why do they pant so much?"],
        "safe_ai_response_rules": ["Advise vet check for any lumps", "Fainting is a cardiac emergency"],
        "vet_escalation_rules": ["Escalate fainting or severe panting", "Escalate bloated abdomen"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Cocker Spaniel",
        "aliases": ["English/American Cocker"],
        "origin_country": "UK",
        "india_commonness_level": "moderate",
        "size_group": "medium",
        "life_expectancy_range": "10-14",
        "male_weight_range_kg": "11-15",
        "female_weight_range_kg": "11-15",
        "height_range_cm": "36-43",
        "coat_type": "long coat",
        "shedding_level": "medium",
        "grooming_need": "high",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 40,
        "apartment_suitability": "good",
        "heat_sensitivity": "low",
        "cold_sensitivity": "low",
        "obesity_risk": "medium",
        "joint_risk": "low",
        "skin_risk": "high",
        "ear_risk": "high",
        "eye_risk": "high",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "medium",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["gentle", "smart", "happy"],
        "training_difficulty": "medium",
        "food_cautions": ["Keep ears out of food bowls if possible (use spaniel bowls)"],
        "nutrition_notes": "Watch for ear infections. Omega-3 for coat health.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Prone to weight gain, feel ribs under thick coat.",
        "puppy_care_notes": "Acclimate to ear cleaning early.",
        "adult_care_notes": "Ear cleaning must be a regular routine due to long, heavy ears.",
        "senior_care_notes": "Monitor for cataracts and glaucoma.",
        "vaccination_context": "Core vaccines.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Ear haematoma", "Progressive retinal atrophy", "IMHA (pale gums, lethargy)"],
        "common_owner_questions": ["Why do their ears smell?", "Why are they shaking their head?"],
        "safe_ai_response_rules": ["Head shaking indicates ear infection; recommend vet"],
        "vet_escalation_rules": ["Escalate pale gums (IMHA risk)", "Escalate cloudy eyes/blindness signs"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Saint Bernard",
        "aliases": ["St. Bernard"],
        "origin_country": "Switzerland",
        "india_commonness_level": "rare",
        "size_group": "giant",
        "life_expectancy_range": "8-10",
        "male_weight_range_kg": "64-82",
        "female_weight_range_kg": "54-64",
        "height_range_cm": "65-90",
        "coat_type": "double coat",
        "shedding_level": "high",
        "grooming_need": "high",
        "activity_level": "low",
        "exercise_need_minutes_per_day": 30,
        "apartment_suitability": "poor",
        "heat_sensitivity": "high",
        "cold_sensitivity": "low",
        "obesity_risk": "medium",
        "joint_risk": "high",
        "skin_risk": "medium",
        "ear_risk": "low",
        "eye_risk": "medium",
        "respiratory_risk": "low",
        "heart_risk": "high",
        "dental_risk": "low",
        "digestive_sensitivity": "high",
        "behavior_tendency": ["playful", "charming", "inquisitive"],
        "training_difficulty": "medium",
        "food_cautions": ["Bloat risk is high. Do not exercise after meals."],
        "nutrition_notes": "Large-breed diet. Avoid exercise after meals (bloat risk).",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Ribs should be palpable. Excess weight ruins joints.",
        "puppy_care_notes": "Must stay lean while growing. Control exercise.",
        "adult_care_notes": "Keep in air conditioning in Indian climate.",
        "senior_care_notes": "Arthritis management is usually required.",
        "vaccination_context": "Core + Leptospirosis.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Bloat/GDV", "Heatstroke", "Joint pain/collapse"],
        "common_owner_questions": ["How much should they eat?", "Are they okay in hot weather?"],
        "safe_ai_response_rules": ["Always warn about heatstroke in India", "GDV warnings with GI symptoms"],
        "vet_escalation_rules": ["Escalate heat exhaustion", "Escalate unproductive retching"],
        "source_references": ["WSAVA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Chihuahua",
        "aliases": ["Chico"],
        "origin_country": "Mexico",
        "india_commonness_level": "moderate",
        "size_group": "toy",
        "life_expectancy_range": "14-16",
        "male_weight_range_kg": "1.5-3",
        "female_weight_range_kg": "1.5-3",
        "height_range_cm": "15-23",
        "coat_type": "varies",
        "shedding_level": "low",
        "grooming_need": "low",
        "activity_level": "medium",
        "exercise_need_minutes_per_day": 20,
        "apartment_suitability": "good",
        "heat_sensitivity": "low",
        "cold_sensitivity": "high",
        "obesity_risk": "medium",
        "joint_risk": "low",
        "skin_risk": "low",
        "ear_risk": "low",
        "eye_risk": "medium",
        "respiratory_risk": "high",
        "heart_risk": "medium",
        "dental_risk": "high",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["charming", "graceful", "sassy"],
        "training_difficulty": "medium",
        "food_cautions": ["Very prone to hypoglycemia. Feed small amounts often."],
        "nutrition_notes": "Small frequent meals. Hypoglycaemia risk in puppies.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Should have a tiny waist. Overweight Chihuahuas face severe joint issues.",
        "puppy_care_notes": "Rub Karo syrup on gums if showing signs of low blood sugar.",
        "adult_care_notes": "Use a harness to prevent tracheal damage.",
        "senior_care_notes": "Dental care is critical. Heart murmurs are common.",
        "vaccination_context": "Core vaccines. Tiny size — vet must adjust doses/monitor for reactions.",
        "deworming_context": "Every 3 months — weight-adjusted dose.",
        "emergency_red_flags_for_breed": ["Hypoglycaemia", "Tracheal collapse", "Luxating patella", "Head trauma (open fontanelle)"],
        "common_owner_questions": ["Why are they shaking?", "Why the honking cough?"],
        "safe_ai_response_rules": ["Shaking can be cold, fear, or hypoglycemia"],
        "vet_escalation_rules": ["Escalate seizures or extreme lethargy in puppies", "Escalate head trauma"],
        "source_references": ["AAHA"],
        "confidence_level": "high",
        "vet_review_status": "reviewed",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Rajapalayam",
        "aliases": ["Poligar Hound"],
        "origin_country": "India",
        "india_commonness_level": "common",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "32-42",
        "female_weight_range_kg": "32-42",
        "height_range_cm": "65-75",
        "coat_type": "short coat",
        "shedding_level": "low",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "poor",
        "heat_sensitivity": "medium",
        "cold_sensitivity": "low",
        "obesity_risk": "low",
        "joint_risk": "medium",
        "skin_risk": "high",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["loyal", "independent", "guardian"],
        "training_difficulty": "high",
        "food_cautions": ["Avoid allergens if skin issues present."],
        "nutrition_notes": "High-energy sighthound. Protein-rich diet.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Sighthound build, but should have good muscle mass.",
        "puppy_care_notes": "Socialize heavily. Test for congenital deafness (BAER test).",
        "adult_care_notes": "Pink skin is prone to sunburn and skin infections in high humidity.",
        "senior_care_notes": "Monitor joint health.",
        "vaccination_context": "Core vaccines essential.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Congenital deafness (white coat gene)", "Severe skin infections in humidity"],
        "common_owner_questions": ["Why is my dog ignoring me? (Could be deaf)", "How to treat red skin?"],
        "safe_ai_response_rules": ["Highlight deafness risk for training issues"],
        "vet_escalation_rules": ["Escalate severe spreading skin lesions"],
        "source_references": ["KCI India", "WSAVA"],
        "confidence_level": "medium",
        "vet_review_status": "needs_vet_review",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Kombai",
        "aliases": ["Combai", "Indian Bear Hound"],
        "origin_country": "India",
        "india_commonness_level": "moderate",
        "size_group": "medium",
        "life_expectancy_range": "12-15",
        "male_weight_range_kg": "20-30",
        "female_weight_range_kg": "20-30",
        "height_range_cm": "50-65",
        "coat_type": "short coat",
        "shedding_level": "low",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 60,
        "apartment_suitability": "moderate",
        "heat_sensitivity": "low",
        "cold_sensitivity": "medium",
        "obesity_risk": "low",
        "joint_risk": "low",
        "skin_risk": "low",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "low",
        "behavior_tendency": ["fierce", "loyal", "intelligent"],
        "training_difficulty": "high",
        "food_cautions": ["None specific, hardy digestively"],
        "nutrition_notes": "Hardy native breed. Balanced diet. Avoid overfeeding.",
        "ideal_bcs_target": "4-5",
        "bcs_interpretation_notes": "Athletic and lean.",
        "puppy_care_notes": "Needs firm, consistent training and early socialization to prevent aggression.",
        "adult_care_notes": "High exercise requirement to keep them mentally stimulated.",
        "senior_care_notes": "Generally very healthy into old age.",
        "vaccination_context": "Core vaccines — often under-vaccinated in rural areas.",
        "deworming_context": "Every 3 months — high parasite exposure.",
        "emergency_red_flags_for_breed": ["Aggression if under-socialised", "Parasites in rural settings"],
        "common_owner_questions": ["How to stop aggression?", "Are they good with kids?"],
        "safe_ai_response_rules": ["Recommend professional trainer for behavior issues"],
        "vet_escalation_rules": ["Escalate signs of tick fever"],
        "source_references": ["KCI India"],
        "confidence_level": "medium",
        "vet_review_status": "needs_vet_review",
        "last_reviewed_date": datetime.utcnow()
    },
    {
        "breed_name": "Mudhol Hound",
        "aliases": ["Caravan Hound", "Pashmi"],
        "origin_country": "India",
        "india_commonness_level": "moderate",
        "size_group": "large",
        "life_expectancy_range": "10-12",
        "male_weight_range_kg": "22-28",
        "female_weight_range_kg": "22-28",
        "height_range_cm": "68-72",
        "coat_type": "short coat",
        "shedding_level": "low",
        "grooming_need": "low",
        "activity_level": "high",
        "exercise_need_minutes_per_day": 75,
        "apartment_suitability": "poor",
        "heat_sensitivity": "low",
        "cold_sensitivity": "high",
        "obesity_risk": "low",
        "joint_risk": "medium",
        "skin_risk": "high",
        "ear_risk": "low",
        "eye_risk": "low",
        "respiratory_risk": "low",
        "heart_risk": "low",
        "dental_risk": "low",
        "digestive_sensitivity": "medium",
        "behavior_tendency": ["aloof", "loyal", "graceful"],
        "training_difficulty": "medium",
        "food_cautions": ["Very low body fat, needs high-quality protein."],
        "nutrition_notes": "Sighthound — very lean body. High protein. Avoid overfeeding.",
        "ideal_bcs_target": "4",
        "bcs_interpretation_notes": "Sighthound standard: ribs, vertebrae, and hip bones may be slightly visible.",
        "puppy_care_notes": "Protect from cold. Needs open space to run.",
        "adult_care_notes": "Thin skin is prone to cuts and tears.",
        "senior_care_notes": "Provide soft bedding to prevent pressure sores.",
        "vaccination_context": "Core vaccines. Often under-vaccinated in Deccan region.",
        "deworming_context": "Every 3 months.",
        "emergency_red_flags_for_breed": ["Anaesthesia sensitivity (sighthound)", "Thin skin wound infections", "Severe weight loss"],
        "common_owner_questions": ["Is my dog too skinny?", "Why do they sleep so much?"],
        "safe_ai_response_rules": ["Sighthounds are naturally skinny, don't automatically diagnose underweight", "Warn about anesthesia risks"],
        "vet_escalation_rules": ["Escalate deep wounds or infections", "Escalate sudden severe weight loss"],
        "source_references": ["KCI India", "WSAVA"],
        "confidence_level": "medium",
        "vet_review_status": "needs_vet_review",
        "last_reviewed_date": datetime.utcnow()
    }
]

def seed():
    print(f"[seed_breeds] {len(BREEDS_DATA)} breeds ready to seed.")
    for b in BREEDS_DATA:
        print(f"  ✓ {b['breed_name']} — {b['size_group']} | obesity:{b['obesity_risk']} | heat:{b['heat_sensitivity']}")
    print("[seed_breeds] Connect SQLAlchemy session to persist to database.")

def seed_to_db(db):
    """Call with active SQLAlchemy session to persist."""
    try:
        from app.models.paw_ai_models import BreedProfile
        count = 0
        for data in BREEDS_DATA:
            exists = db.query(BreedProfile).filter_by(breed_name=data["breed_name"]).first()
            if not exists:
                bp = BreedProfile(**data)
                db.add(bp)
                count += 1
            else:
                for k, v in data.items():
                    setattr(exists, k, v)
                count += 1
        db.commit()
        print(f"[seed_breeds] SUCCESS {count} breeds seeded/updated.")
    except Exception as e:
        db.rollback()
        print(f"[seed_breeds] ERROR: {e}")

if __name__ == "__main__":
    seed()
