"""paw_ai

Revision ID: 8931a6352851
Revises: 
Create Date: 2026-05-15 22:46:55.653501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8931a6352851'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed_profiles',
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.Column('breed_name', sa.String(length=120), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('origin_country', sa.String(length=80), nullable=True),
    sa.Column('india_commonness_level', sa.String(length=20), nullable=True),
    sa.Column('size_group', sa.String(length=20), nullable=True),
    sa.Column('life_expectancy_range', sa.String(length=20), nullable=True),
    sa.Column('male_weight_range_kg', sa.String(length=20), nullable=True),
    sa.Column('female_weight_range_kg', sa.String(length=20), nullable=True),
    sa.Column('height_range_cm', sa.String(length=20), nullable=True),
    sa.Column('coat_type', sa.String(length=60), nullable=True),
    sa.Column('shedding_level', sa.String(length=20), nullable=True),
    sa.Column('grooming_need', sa.String(length=20), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('exercise_need_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('apartment_suitability', sa.String(length=20), nullable=True),
    sa.Column('heat_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('cold_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('obesity_risk', sa.String(length=20), nullable=True),
    sa.Column('joint_risk', sa.String(length=20), nullable=True),
    sa.Column('skin_risk', sa.String(length=20), nullable=True),
    sa.Column('ear_risk', sa.String(length=20), nullable=True),
    sa.Column('eye_risk', sa.String(length=20), nullable=True),
    sa.Column('respiratory_risk', sa.String(length=20), nullable=True),
    sa.Column('heart_risk', sa.String(length=20), nullable=True),
    sa.Column('dental_risk', sa.String(length=20), nullable=True),
    sa.Column('digestive_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('behavior_tendency', sa.JSON(), nullable=True),
    sa.Column('training_difficulty', sa.String(length=20), nullable=True),
    sa.Column('food_cautions', sa.JSON(), nullable=True),
    sa.Column('nutrition_notes', sa.Text(), nullable=True),
    sa.Column('ideal_bcs_target', sa.String(length=10), nullable=True),
    sa.Column('bcs_interpretation_notes', sa.Text(), nullable=True),
    sa.Column('puppy_care_notes', sa.Text(), nullable=True),
    sa.Column('adult_care_notes', sa.Text(), nullable=True),
    sa.Column('senior_care_notes', sa.Text(), nullable=True),
    sa.Column('vaccination_context', sa.Text(), nullable=True),
    sa.Column('deworming_context', sa.Text(), nullable=True),
    sa.Column('emergency_red_flags_for_breed', sa.JSON(), nullable=True),
    sa.Column('common_owner_questions', sa.JSON(), nullable=True),
    sa.Column('safe_ai_response_rules', sa.JSON(), nullable=True),
    sa.Column('vet_escalation_rules', sa.JSON(), nullable=True),
    sa.Column('source_references', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('vet_review_status', sa.String(length=30), nullable=True),
    sa.Column('last_reviewed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('breed_id')
    )
    op.create_index(op.f('ix_breed_profiles_breed_name'), 'breed_profiles', ['breed_name'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('encrypt_health_data', sa.Boolean(), nullable=True),
    sa.Column('consent_for_ai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('breed_activity_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=60), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed_profiles.breed_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_activity_rules_breed_id'), 'breed_activity_rules', ['breed_id'], unique=False)
    op.create_table('breed_health_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('risk_name', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breed_profiles.breed_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_health_risks_breed_id'), 'breed_health_risks', ['breed_id'], unique=False)
    op.create_table('breed_nutrition_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed_profiles.breed_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_nutrition_rules_breed_id'), 'breed_nutrition_rules', ['breed_id'], unique=False)
    op.create_table('dog_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('breed_type', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_condition_status', sa.String(), nullable=True),
    sa.Column('diet_type', sa.String(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('health_goal', sa.String(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('past_illnesses', sa.JSON(), nullable=True),
    sa.Column('vaccine_status', sa.String(), nullable=True),
    sa.Column('deworming_status', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dog_profiles_id'), 'dog_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_dog_profiles_user_id'), 'dog_profiles', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_email', sa.String(), nullable=True),
    sa.Column('vaccines', sa.Boolean(), nullable=True),
    sa.Column('deworming', sa.Boolean(), nullable=True),
    sa.Column('vet_visits', sa.Boolean(), nullable=True),
    sa.Column('nutrition', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('owner_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_owner_profiles_id'), 'owner_profiles', ['id'], unique=False)
    op.create_table('vet_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('vet_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vet_profiles_id'), 'vet_profiles', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('bcs_bmi_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('bcs_score', sa.Integer(), nullable=True),
    sa.Column('bmi_value', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('rer_kcal', sa.Float(), nullable=True),
    sa.Column('daily_cal_estimate', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcs_bmi_records_dog_id'), 'bcs_bmi_records', ['dog_id'], unique=False)
    op.create_table('behavior_logs_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('behavior_type', sa.String(length=80), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_logs_v2_dog_id'), 'behavior_logs_v2', ['dog_id'], unique=False)
    op.create_index(op.f('ix_behavior_logs_v2_logged_at'), 'behavior_logs_v2', ['logged_at'], unique=False)
    op.create_table('deworming_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('date_given', sa.DateTime(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('weight_at_treatment', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deworming_records_dog_id'), 'deworming_records', ['dog_id'], unique=False)
    op.create_index(op.f('ix_deworming_records_id'), 'deworming_records', ['id'], unique=False)
    op.create_index(op.f('ix_deworming_records_next_due_date'), 'deworming_records', ['next_due_date'], unique=False)
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=True)
    op.create_table('medical_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('diagnosed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_dog_id'), 'medical_history', ['dog_id'], unique=False)
    op.create_index(op.f('ix_medical_history_id'), 'medical_history', ['id'], unique=False)
    op.create_table('nutrition_logs_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('amount_g', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_v2_dog_id'), 'nutrition_logs_v2', ['dog_id'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_v2_logged_at'), 'nutrition_logs_v2', ['logged_at'], unique=False)
    op.create_table('paw_ai_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('session_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paw_ai_sessions_dog_id'), 'paw_ai_sessions', ['dog_id'], unique=False)
    op.create_index(op.f('ix_paw_ai_sessions_started_at'), 'paw_ai_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_paw_ai_sessions_user_id'), 'paw_ai_sessions', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_dog_id'), 'reports', ['dog_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('symptom_triage_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('severity_level', sa.String(), nullable=True),
    sa.Column('triage_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_triage_sessions_created_at'), 'symptom_triage_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_symptom_triage_sessions_dog_id'), 'symptom_triage_sessions', ['dog_id'], unique=False)
    op.create_index(op.f('ix_symptom_triage_sessions_id'), 'symptom_triage_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_triage_sessions_severity_level'), 'symptom_triage_sessions', ['severity_level'], unique=False)
    op.create_table('vaccine_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_given', sa.DateTime(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccine_records_dog_id'), 'vaccine_records', ['dog_id'], unique=False)
    op.create_index(op.f('ix_vaccine_records_id'), 'vaccine_records', ['id'], unique=False)
    op.create_index(op.f('ix_vaccine_records_next_due_date'), 'vaccine_records', ['next_due_date'], unique=False)
    op.create_table('vet_visit_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('vet_name', sa.String(), nullable=True),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('reason_for_visit', sa.String(), nullable=True),
    sa.Column('vet_remarks', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('medicines_prescribed', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vet_visit_summaries_dog_id'), 'vet_visit_summaries', ['dog_id'], unique=False)
    op.create_index(op.f('ix_vet_visit_summaries_id'), 'vet_visit_summaries', ['id'], unique=False)
    op.create_table('vision_scan_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('severity_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_scan_records_created_at'), 'vision_scan_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_vision_scan_records_dog_id'), 'vision_scan_records', ['dog_id'], unique=False)
    op.create_index(op.f('ix_vision_scan_records_id'), 'vision_scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_vision_scan_records_scan_type'), 'vision_scan_records', ['scan_type'], unique=False)
    op.create_index(op.f('ix_vision_scan_records_severity_level'), 'vision_scan_records', ['severity_level'], unique=False)
    op.create_table('emergency_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('action_required', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_triage_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_classifications_id'), 'emergency_classifications', ['id'], unique=False)
    op.create_table('paw_ai_context_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paw_ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paw_ai_context_snapshots_session_id'), 'paw_ai_context_snapshots', ['session_id'], unique=False)
    op.create_table('paw_ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=60), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['paw_ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paw_ai_messages_session_id'), 'paw_ai_messages', ['session_id'], unique=False)
    op.create_table('paw_ai_safety_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(length=60), nullable=False),
    sa.Column('trigger_content', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['paw_ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paw_ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('visited_vet', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['paw_ai_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['paw_ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paw_ai_feedback')
    op.drop_table('paw_ai_safety_logs')
    op.drop_index(op.f('ix_paw_ai_messages_session_id'), table_name='paw_ai_messages')
    op.drop_table('paw_ai_messages')
    op.drop_index(op.f('ix_paw_ai_context_snapshots_session_id'), table_name='paw_ai_context_snapshots')
    op.drop_table('paw_ai_context_snapshots')
    op.drop_index(op.f('ix_emergency_classifications_id'), table_name='emergency_classifications')
    op.drop_table('emergency_classifications')
    op.drop_index(op.f('ix_vision_scan_records_severity_level'), table_name='vision_scan_records')
    op.drop_index(op.f('ix_vision_scan_records_scan_type'), table_name='vision_scan_records')
    op.drop_index(op.f('ix_vision_scan_records_id'), table_name='vision_scan_records')
    op.drop_index(op.f('ix_vision_scan_records_dog_id'), table_name='vision_scan_records')
    op.drop_index(op.f('ix_vision_scan_records_created_at'), table_name='vision_scan_records')
    op.drop_table('vision_scan_records')
    op.drop_index(op.f('ix_vet_visit_summaries_id'), table_name='vet_visit_summaries')
    op.drop_index(op.f('ix_vet_visit_summaries_dog_id'), table_name='vet_visit_summaries')
    op.drop_table('vet_visit_summaries')
    op.drop_index(op.f('ix_vaccine_records_next_due_date'), table_name='vaccine_records')
    op.drop_index(op.f('ix_vaccine_records_id'), table_name='vaccine_records')
    op.drop_index(op.f('ix_vaccine_records_dog_id'), table_name='vaccine_records')
    op.drop_table('vaccine_records')
    op.drop_index(op.f('ix_symptom_triage_sessions_severity_level'), table_name='symptom_triage_sessions')
    op.drop_index(op.f('ix_symptom_triage_sessions_id'), table_name='symptom_triage_sessions')
    op.drop_index(op.f('ix_symptom_triage_sessions_dog_id'), table_name='symptom_triage_sessions')
    op.drop_index(op.f('ix_symptom_triage_sessions_created_at'), table_name='symptom_triage_sessions')
    op.drop_table('symptom_triage_sessions')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_dog_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_paw_ai_sessions_user_id'), table_name='paw_ai_sessions')
    op.drop_index(op.f('ix_paw_ai_sessions_started_at'), table_name='paw_ai_sessions')
    op.drop_index(op.f('ix_paw_ai_sessions_dog_id'), table_name='paw_ai_sessions')
    op.drop_table('paw_ai_sessions')
    op.drop_index(op.f('ix_nutrition_logs_v2_logged_at'), table_name='nutrition_logs_v2')
    op.drop_index(op.f('ix_nutrition_logs_v2_dog_id'), table_name='nutrition_logs_v2')
    op.drop_table('nutrition_logs_v2')
    op.drop_index(op.f('ix_medical_history_id'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_dog_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    op.drop_index(op.f('ix_deworming_records_next_due_date'), table_name='deworming_records')
    op.drop_index(op.f('ix_deworming_records_id'), table_name='deworming_records')
    op.drop_index(op.f('ix_deworming_records_dog_id'), table_name='deworming_records')
    op.drop_table('deworming_records')
    op.drop_index(op.f('ix_behavior_logs_v2_logged_at'), table_name='behavior_logs_v2')
    op.drop_index(op.f('ix_behavior_logs_v2_dog_id'), table_name='behavior_logs_v2')
    op.drop_table('behavior_logs_v2')
    op.drop_index(op.f('ix_bcs_bmi_records_dog_id'), table_name='bcs_bmi_records')
    op.drop_table('bcs_bmi_records')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vet_profiles_id'), table_name='vet_profiles')
    op.drop_table('vet_profiles')
    op.drop_index(op.f('ix_owner_profiles_id'), table_name='owner_profiles')
    op.drop_table('owner_profiles')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_dog_profiles_user_id'), table_name='dog_profiles')
    op.drop_index(op.f('ix_dog_profiles_id'), table_name='dog_profiles')
    op.drop_table('dog_profiles')
    op.drop_index(op.f('ix_breed_nutrition_rules_breed_id'), table_name='breed_nutrition_rules')
    op.drop_table('breed_nutrition_rules')
    op.drop_index(op.f('ix_breed_health_risks_breed_id'), table_name='breed_health_risks')
    op.drop_table('breed_health_risks')
    op.drop_index(op.f('ix_breed_activity_rules_breed_id'), table_name='breed_activity_rules')
    op.drop_table('breed_activity_rules')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_breed_profiles_breed_name'), table_name='breed_profiles')
    op.drop_table('breed_profiles')
    # ### end Alembic commands ###
